name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github Issue Context
        run: echo '${{ toJson(github.event.issue)}}' | jq
        shell: bash
      - name: Github Issue Title & Body
        run: echo "Title':' ${{ github.event.issue.title }} Body':' ${{ github.event.issue.body}}"
