name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github Issue Context
        run: echo '${{ toJson(github.event.issue)}}' | jq
        shell: bash
      - name: Github Issue Title & Body
        run: echo "${{ github.event.issue.title }} - ${{ github.event.issue.body}}"
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number}}
          body: |
            This is a multi-line text comment
            - With GitHub **markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"
